#############################################################
#                   CONFIGURATION
#############################################################
@hostname = http://localhost:8080
@rpi_hostname = http://192.168.1.213:8080


#############################################################
#               LOCAL TESTS (MACOS / IDE)
#############################################################

### LOGIN (LOCALLY)
# @name login_local
POST {{hostname}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### List root folder (admin)
GET {{hostname}}/api/files/list
Authorization: Bearer {{login_local.response.body.token}}

### List subfolder (admin/testy)
GET {{hostname}}/api/files/list?path=testy
Authorization: Bearer {{login_local.response.body.token}}

### List trash (admin/trash)
GET {{hostname}}/api/files/list?path=trash
Authorization: Bearer {{login_local.response.body.token}}

### Create a new virtual folder (admin/nowy_folder)
# @name create_folder
POST {{hostname}}/api/files/folders/create
Authorization: Bearer {{login_local.response.body.token}}
Content-Type: application/json

{
    "logicalPath": "nowy_folder"
}

### Upload a text file (to admin/testy)
POST {{hostname}}/api/files/upload?path=testy
Authorization: Bearer {{login_local.response.body.token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="plik.txt"
Content-Type: text/plain

< /Users/sqstudio/Desktop/plik.txt
--WebAppBoundary--

### Upload a multimedia file (to admin/testy)
POST {{hostname}}/api/files/upload?path=testy
Authorization: Bearer {{login_local.response.body.token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="zdjecie.png"
Content-Type: image/png

< /Users/sqstudio/Desktop/zdjecie.png
--WebAppBoundary--

### Upload a file that is too big (to admin/testy)
POST {{hostname}}/api/files/upload?path=testy
Authorization: Bearer {{login_local.response.body.token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="mock.png"
Content-Type: image/png

< /Users/sqstudio/Desktop/mock.png
--WebAppBoundary--

### Move/Rename a file (from testy/plik.txt to plik.txt)
PUT {{hostname}}/api/files/move
Authorization: Bearer {{login_local.response.body.token}}
Content-Type: application/json

{
    "fromPath": "testy/plik.txt",
    "toPath": "plik.txt"
}

### Delete a file (to trash)
DELETE {{hostname}}/api/files/delete?path=plik.txt
Authorization: Bearer {{login_local.response.body.token}}

### Restore a file from trash
POST {{hostname}}/api/files/restore
Authorization: Bearer {{login_local.response.body.token}}
Content-Type: application/json

{
    "logicalPath": "admin/trash/plik.txt"
}

### Get recent files
GET {{hostname}}/api/files/recent
Authorization: Bearer {{login_local.response.body.token}}

### Get recent MEDIA files
GET {{hostname}}/api/files/recent?multimediaOnly=true
Authorization: Bearer {{login_local.response.body.token}}

### Get system stats (Mocked on Mac)
GET {{hostname}}/api/system/stats
Authorization: Bearer {{login_local.response.body.token}}

### Logout
POST {{hostname}}/api/auth/logout
Authorization: Bearer {{login_local.response.body.token}}

### Get Event Logs
GET {{hostname}}/api/system/logs/events
Authorization: Bearer {{login_local.response.body.token}}

### Get Transfer Logs
GET {{hostname}}/api/system/logs/transfers
Authorization: Bearer {{login_local.response.body.token}}

### Get System Logs
GET {{hostname}}/api/system/logs/system
Authorization: Bearer {{login_local.response.body.token}}

### Start File Backup
POST {{hostname}}/api/system/backup/start
Authorization: Bearer {{login_local.response.body.token}}


#############################################################
#               REMOTE TESTS (RASPBERRY PI)
#############################################################

### LOGIN (ON RASPBERRY PI)
# @name login_rpi
POST {{rpi_hostname}}/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### List root folder (admin)
GET {{rpi_hostname}}/api/files/list
Authorization: Bearer {{login_rpi.response.body.token}}

### List subfolder (admin/testy)
GET {{rpi_hostname}}/api/files/list?path=testy
Authorization: Bearer {{login_rpi.response.body.token}}

### List trash (admin/trash)
GET {{rpi_hostname}}/api/files/list?path=trash
Authorization: Bearer {{login_rpi.response.body.token}}

### Create folder on RPi (admin/testy)
POST {{rpi_hostname}}/api/files/folders/create
Authorization: Bearer {{login_rpi.response.body.token}}
Content-Type: application/json

{
    "logicalPath": "testy"
}

### Upload a text file to RPi (to admin/testy)
POST {{rpi_hostname}}/api/files/upload?path=testy
Authorization: Bearer {{login_rpi.response.body.token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="plik.txt"
Content-Type: text/plain

< /Users/sqstudio/Desktop/plik.txt
--WebAppBoundary--

### Upload a multimedia file to RPi (to admin/testy)
POST {{rpi_hostname}}/api/files/upload?path=testy
Authorization: Bearer {{login_rpi.response.body.token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="zdjecie.png"
Content-Type: image/png

< /Users/sqstudio/Desktop/zdjecie.png
--WebAppBoundary--

### Upload a file that is too big (to admin/testy)
POST {{rpi_hostname}}/api/files/upload?path=testy
Authorization: Bearer {{login_rpi.response.body.token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="mock.png"
Content-Type: image/png

< /Users/sqstudio/Desktop/mock.png
--WebAppBoundary--

### Move/Rename file on RPi
PUT {{rpi_hostname}}/api/files/move
Authorization: Bearer {{login_rpi.response.body.token}}
Content-Type: application/json

{
    "fromPath": "testy/plik.txt",
    "toPath": "plik.txt"
}

### Delete file on RPi (to trash)
DELETE {{rpi_hostname}}/api/files/delete?path=plik.txt
Authorization: Bearer {{login_rpi.response.body.token}}

### Restore file on RPi
POST {{rpi_hostname}}/api/files/restore
Authorization: Bearer {{login_rpi.response.body.token}}
Content-Type: application/json

{
    "logicalPath": "admin/trash/plik.txt"
}

### Get recent files on RPi
GET {{rpi_hostname}}/api/files/recent
Authorization: Bearer {{login_rpi.response.body.token}}

### Get recent MEDIA files on RPi
GET {{rpi_hostname}}/api/files/recent?multimediaOnly=true
Authorization: Bearer {{login_rpi.response.body.token}}

### Get system stats (Real data from RPi)
GET {{rpi_hostname}}/api/system/stats
Authorization: Bearer {{login_rpi.response.body.token}}

### Logout from RPi
POST {{rpi_hostname}}/api/auth/logout
Authorization: Bearer {{login_rpi.response.body.token}}

### (RED BUTTON #1) Reboot RPi
POST {{rpi_hostname}}/api/system/reboot
Authorization: Bearer {{login_rpi.response.body.token}}

### (RED BUTTON #2) Shutdown RPi
POST {{rpi_hostname}}/api/system/shutdown
Authorization: Bearer {{login_rpi.response.body.token}}

### Get Event Logs
GET {{rpi_hostname}}/api/system/logs/events
Authorization: Bearer {{login_rpi.response.body.token}}

### Get Transfer Logs
GET {{rpi_hostname}}/api/system/logs/transfers
Authorization: Bearer {{login_rpi.response.body.token}}

### Get System Logs
GET {{rpi_hostname}}/api/system/logs/system
Authorization: Bearer {{login_rpi.response.body.token}}

### Start File Backup
POST {{rpi_hostname}}/api/system/backup/start
Authorization: Bearer {{login_rpi.response.body.token}}