@token = cf9bcd7f-58ce-4b1d-9f8a-71e7a405dd99

### Login
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Lista plików w folderze root
GET http://localhost:8080/api/files/list
Authorization: Bearer {{token}}

### Lista plików w folderze root/testy
GET http://localhost:8080/api/files/list?path=testy
Authorization: Bearer {{token}}

### Lista plików w koszu
GET http://localhost:8080/api/files/list?path=trash
Authorization: Bearer {{token}}

### Lista ostatnio dodanych plików
GET http://localhost:8080/api/files/recent
Authorization: Bearer {{token}}

### Lista ostatnio dodanych plików multimedialnych
GET http://localhost:8080/api/files/recent?multimediaOnly=true
Authorization: Bearer {{token}}

### Upload pliku
POST http://localhost:8080/api/files/upload?path=testy
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="plik.txt"
Content-Type: text/plain

< /Users/sqstudio/Desktop/plik.txt
--WebAppBoundary--

### Upload pliku multimedialnego
POST http://localhost:8080/api/files/upload?path=testy
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="zdjecie.png"
Content-Type: image/png

< /Users/sqstudio/Desktop/zdjecie.png
--WebAppBoundary--

### Przenies plik

PUT http://localhost:8080/api/files/move
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "fromPath": "testy/plik.txt",
    "toPath": "plik.txt"
}

### Usuń plik
DELETE http://localhost:8080/api/files/delete?path=testy/plik.txt
Authorization: Bearer {{token}}

### Logout
POST http://localhost:8080/api/auth/logout
Authorization: Bearer {{token}}

### System monitor
GET http://localhost:8080/api/system/stats
Authorization: Bearer {{token}}


#########################

# RASPBERRY TESTS

#########################


### Login
POST http://192.168.1.213:8080/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Lista plików
GET http://192.168.1.213:8080/api/files/list?path=testy
Authorization: Bearer {{token}}

### Lista plików w koszu
GET http://192.168.1.213:8080/api/files/list?path=trash
Authorization: Bearer {{token}}

### Upload pliku
POST http://192.168.1.213:8080/api/files/upload?path=testy
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="plik.txt"
Content-Type: text/plain

< /Users/sqstudio/Desktop/plik.txt
--WebAppBoundary--

### Usuń plik
DELETE http://192.168.1.213:8080/api/files/delete?path=testy/plik.txt
Authorization: Bearer {{token}}

### Logout
POST http://192.168.1.213:8080/api/auth/logout
Authorization: Bearer {{token}}

### System monitor
GET http://192.168.1.213:8080/api/system/stats
Authorization: Bearer {{token}}

### System reboot
POST http://192.168.1.213:8080/api/system/reboot
Authorization: Bearer {{token}}

### System shutdown
POST http://192.168.1.213:8080/api/system/shutdown
Authorization: Bearer {{token}}